dist: xenial   # required for Python >= 3.7
env:
  global:
    - CC_TEST_REPORTER_ID=$CODE_CLIMATE_REPORTER_ID
    - LANGMODELSPATH="$TRAVIS_BUILD_DIR/data/models"
    - LANGMODELS_EVALUATION_TEST='true'
language: python
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
      before_script: echo "Not sending code coverage to code climate on OSx"
      after_script: echo "Not sending code coverage to code climate on OSx"
before_install:
  - sudo apt-get install autoconf automake build-essential libtool python-dev # needed to install jq
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - cd $TRAVIS_BUILD_DIR
  - echo "Current directory is $(pwd)"
  - python -W ignore -m doctest -o ELLIPSIS -o NORMALIZE_WHITESPACE README.rst
  - coverage run -m pytest --doctest-modules
  - coverage report -m --include=./\*\* --omit=tests/\*\*,tests-b2b/\*\*,.venv/\*\* --fail-under=60
  - coverage xml -i --include=./\*\* --omit=tests/\*\*,tests-b2b/\*\*,.venv/\*\*
after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then echo "Reporting coverage to Code Climate" && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
