dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
jobs:
  include:
    - os: osx
      language: sh
      python: "3.7"
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - systeminfo
        - export MINICONDA=/c/miniconda
        - MINICONDA_WIN=$(cygpath --windows $MINICONDA)
        - choco install openssl.light
        - choco install miniconda3 --params="'/AddToPath:0 /D:$MINICONDA_WIN'"
        - source $MINICONDA/Scripts/activate
        - source $MINICONDA/etc/profile.d/conda.sh
        - hash -r
        - conda config --set always_yes yes
        - conda info -a
        - conda config --add channels conda-forge
        - conda create -q -n testenv python=3.7
        - conda activate testenv
        - conda list
      install:
        - conda install matplotlib
        - conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
install:
  - pip3 install torch==1.3.0
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - cd $TRAVIS_BUILD_DIR
  - echo "Current directory is $(pwd)"
  - coverage run -m pytest --doctest-modules
  - coverage report -m
  - coverage xml -i
