version: 1
disable_existing_loggers: False
formatters:
  with_process_name:
    format: "%(asctime)s [%(name)s] %(levelname)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: with_process_name
    stream: ext://sys.stdout
loggers:
  langmodels.training:
    level: DEBUG
    propagate: True
root:
  level: DEBUG
  handlers: [console]