CONVERTERS_PREFIX = '_converters'
SERVER_URL = 'https://www.inf.unibz.it'
MODEL_DIR_URL = SERVER_URL + '/~hbabii/pretrained_models'
CONVERTERS_URL= MODEL_DIR_URL + CONVERTERS_PREFIX
LIST_PREFIX = '_list'
MODEL_LIST_URL = MODEL_DIR_URL + LIST_PREFIX
PATH_TO_MODELS_ON_SERVER = '/home/students/hbabii/public_html/pretrained_models'
SERVER_HOST_NAME = 'actarus.inf.unibz.it'
PATH_TO_LOGS_ON_SERVER = '.pysftp.log'